version: "3.8"

services:
  app:
    container_name: chanjoke-patient
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    environment:
      - NODE_ENV=production
    ports:
      - 80:80