version: "3.8"

services:
  app:
    container_name: docker-chanjoke-patient-c
    image: docker-chanjoke-patient-i
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
