FROM node:20 as build
WORKDIR /app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install --quiet

COPY . .

RUN npm run build



RUN npm install -g serve


CMD ["serve", "-s", "dist", "-l", "3000"]
